## Preprocessing

In [69]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [70]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=["EIN","NAME"])

In [71]:
# Determine the number of unique values in each column.
#syntax reference: https://note.nkmk.me/en/python-pandas-value-counts/#:~:text=nunique()%20on%20DataFrame%20returns,each%20column%20as%20a%20Series%20.&text=Similar%20to%20Series%20%2C%20the%20nunique,the%20count%20to%20row%2Dwise.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [72]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_type_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [73]:
temp_df = pd.DataFrame({
    "a": ['yes', 'no', 'mayber'],
    "b": [1,2,3],
    "c": ["male", "female", "female"]
})

pd.get_dummies(temp_df)

   b  a_mayber   a_no  a_yes  c_female  c_male
0  1     False  False   True     False    True
1  2     False   True  False      True   False
2  3      True  False  False      True   False

In [74]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_type_counts[application_type_counts.values < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [75]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_type_counts = application_df["CLASSIFICATION"].value_counts()
classification_type_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [76]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_type_counts[classification_type_counts.values > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [77]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_type_counts[classification_type_counts.values < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [78]:
# Convert categorical data to numeric with `pd.get_dummies`
dummies_df = pd.get_dummies(application_df)
dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,False,False,False,True,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [79]:
# Split our preprocessed data into our features and target arrays
y = dummies_df["IS_SUCCESSFUL"].values
X = dummies_df.drop("IS_SUCCESSFUL", axis=1).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [80]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [81]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 50
hidden_nodes_layer3 = 25
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

C:\Users\HP\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                     │ (None, 50)                  │           2,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 50)                  │           2,550 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 25)                  │           1,275 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 1)                   │              26 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,051 (23.64 KB)

 Trainable params: 6,051 (23.64 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])

In [83]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 3s 992us/step - accuracy: 0.6792 - loss: 0.6031
Epoch 2/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 982us/step - accuracy: 0.7277 - loss: 0.5556
Epoch 3/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 939us/step - accuracy: 0.7322 - loss: 0.5513
Epoch 4/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - accuracy: 0.7312 - loss: 0.5517
Epoch 5/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7324 - loss: 0.5471
Epoch 6/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7343 - loss: 0.5449
Epoch 7/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7338 - loss: 0.5456
Epoch 8/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7340 - loss: 0.5465
Epoch 9/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 942us/step - accuracy: 0.7296 - loss: 0.5502
Epoch 10/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 982us/step - accuracy: 0.7331 - loss: 0.5473
Epoch 11/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 960us/step - accuracy: 0.7326 - loss: 0.5442
Epoch 12/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 906us/step - accuracy: 0.7345 - loss: 0.5438
Epoch 13/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7366 - loss: 0.5388
Epoch 14/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 945us/step - accuracy: 0.7366 - loss: 0.5418
Epoch 15/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 988us/step - accuracy: 0.7336 - loss: 0.5454
Epoch 16/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 928us/step - accuracy: 0.7392 - loss: 0.5431
Epoch 17/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.7288 - loss: 0.5488
Epoch 18/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7415 - loss: 0.5374
Epoch 19/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 909us/step - accuracy: 0.7395 - loss: 0.5363
Epoch 20/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 957us/step - accuracy: 0.7362 - loss: 0.5408
Epoch 21/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 995us/step - accuracy: 0.7364 - loss: 0.5404
Epoch 22/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.7398 - loss: 0.5383
Epoch 23/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.7355 - loss: 0.5433
Epoch 24/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 954us/step - accuracy: 0.7353 - loss: 0.5434
Epoch 25/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 964us/step - accuracy: 0.7359 - loss: 0.5414
Epoch 26/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.7375 - loss: 0.5394
Epoch 27/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 957us/step - accuracy: 0.7348 - loss: 0.5418
Epoch 28/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 992us/step - accuracy: 0.7368 - loss: 0.5426
Epoch 29/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 976us/step - accuracy: 0.7387 - loss: 0.5381
Epoch 30/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7363 - loss: 0.5407
Epoch 31/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 989us/step - accuracy: 0.7377 - loss: 0.5382
Epoch 32/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 976us/step - accuracy: 0.7354 - loss: 0.5400
Epoch 33/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7427 - loss: 0.5354
Epoch 34/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 980us/step - accuracy: 0.7340 - loss: 0.5385
Epoch 35/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 923us/step - accuracy: 0.7366 - loss: 0.5380
Epoch 36/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7371 - loss: 0.5381
Epoch 37/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 991us/step - accuracy: 0.7358 - loss: 0.5396
Epoch 38/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 951us/step - accuracy: 0.7345 - loss: 0.5411
Epoch 39/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 948us/step - accuracy: 0.7417 - loss: 0.5351
Epoch 40/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 985us/step - accuracy: 0.7390 - loss: 0.5351
Epoch 41/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 943us/step - accuracy: 0.7404 - loss: 0.5321
Epoch 42/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.7370 - loss: 0.5379
Epoch 43/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 999us/step - accuracy: 0.7397 - loss: 0.5361
Epoch 44/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7391 - loss: 0.5377
Epoch 45/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 960us/step - accuracy: 0.7438 - loss: 0.5331
Epoch 46/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 977us/step - accuracy: 0.7369 - loss: 0.5368
Epoch 47/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 948us/step - accuracy: 0.7363 - loss: 0.5390
Epoch 48/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 934us/step - accuracy: 0.7364 - loss: 0.5393
Epoch 49/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 986us/step - accuracy: 0.7386 - loss: 0.5374
Epoch 50/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 948us/step - accuracy: 0.7417 - loss: 0.5331
Epoch 51/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 940us/step - accuracy: 0.7402 - loss: 0.5351
Epoch 52/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 970us/step - accuracy: 0.7380 - loss: 0.5359
Epoch 53/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 943us/step - accuracy: 0.7394 - loss: 0.5379
Epoch 54/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 970us/step - accuracy: 0.7345 - loss: 0.5409
Epoch 55/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7388 - loss: 0.5357
Epoch 56/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 977us/step - accuracy: 0.7344 - loss: 0.5406
Epoch 57/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7386 - loss: 0.5367
Epoch 58/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7375 - loss: 0.5367
Epoch 59/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7410 - loss: 0.5337
Epoch 60/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7399 - loss: 0.5353
Epoch 61/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7382 - loss: 0.5351
Epoch 62/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7416 - loss: 0.5338
Epoch 63/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7389 - loss: 0.5350
Epoch 64/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7392 - loss: 0.5368
Epoch 65/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7463 - loss: 0.5305
Epoch 66/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7397 - loss: 0.5340
Epoch 67/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7439 - loss: 0.5304
Epoch 68/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.7458 - loss: 0.5317
Epoch 69/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7455 - loss: 0.5289
Epoch 70/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7401 - loss: 0.5339
Epoch 71/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7384 - loss: 0.5343
Epoch 72/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 977us/step - accuracy: 0.7402 - loss: 0.5329
Epoch 73/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 937us/step - accuracy: 0.7371 - loss: 0.5359
Epoch 74/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 960us/step - accuracy: 0.7382 - loss: 0.5334
Epoch 75/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 926us/step - accuracy: 0.7408 - loss: 0.5349
Epoch 76/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 978us/step - accuracy: 0.7399 - loss: 0.5350
Epoch 77/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.7467 - loss: 0.5283
Epoch 78/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 959us/step - accuracy: 0.7367 - loss: 0.5388
Epoch 79/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 991us/step - accuracy: 0.7414 - loss: 0.5339
Epoch 80/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.7450 - loss: 0.5291
Epoch 81/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 975us/step - accuracy: 0.7461 - loss: 0.5274
Epoch 82/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 951us/step - accuracy: 0.7410 - loss: 0.5337
Epoch 83/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 996us/step - accuracy: 0.7358 - loss: 0.5360
Epoch 84/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 988us/step - accuracy: 0.7395 - loss: 0.5355
Epoch 85/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - accuracy: 0.7427 - loss: 0.5312
Epoch 86/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 997us/step - accuracy: 0.7411 - loss: 0.5345
Epoch 87/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 976us/step - accuracy: 0.7430 - loss: 0.5290
Epoch 88/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 967us/step - accuracy: 0.7394 - loss: 0.5310
Epoch 89/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7412 - loss: 0.5272
Epoch 90/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 993us/step - accuracy: 0.7425 - loss: 0.5318
Epoch 91/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 959us/step - accuracy: 0.7429 - loss: 0.5320
Epoch 92/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7436 - loss: 0.5288
Epoch 93/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 993us/step - accuracy: 0.7445 - loss: 0.5287
Epoch 94/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 947us/step - accuracy: 0.7431 - loss: 0.5304
Epoch 95/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 993us/step - accuracy: 0.7454 - loss: 0.5288
Epoch 96/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 997us/step - accuracy: 0.7394 - loss: 0.5319
Epoch 97/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 981us/step - accuracy: 0.7409 - loss: 0.5311
Epoch 98/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7409 - loss: 0.5323
Epoch 99/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7393 - loss: 0.5325
Epoch 100/100
804/804 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7423 - loss: 0.5315

In [84]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 1ms/step - accuracy: 0.7285 - loss: 0.5589
Loss: 0.5588968396186829, Accuracy: 0.7285131216049194

In [85]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity16.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.